In [3]:
import numpy as np
from itertools import permutations
from copy import deepcopy

from MSA_class import MultipleSequenceAlignment

In [4]:
my_strings   = np.array(["AC","C"])
my_penalties = np.array([4,4,4])
my_msa     = MultipleSequenceAlignment(strings = my_strings, penalties = my_penalties) 
print("Initial matrix:")
print(my_msa.initial_MSA)
print("corresponding bit string:")
print(my_msa.initial_bitstring)
print("corresponding score weights:")
print(my_msa.score_weights)
print("corresponding QUBO model given as (Q,h,d):")
print(my_msa.QUBO_model)


Initial matrix:
[['A' 'C']
 ['C' '_']]
corresponding bit string:
[1. 0. 0. 1. 1. 0.]
corresponding score weights:
[[ 1.  0.]
 [-1.  0.]]
corresponding QUBO model given as (Q,h,d):
(array([[ 4.,  0.,  4.,  0.,  1.,  0.],
       [ 8.,  4.,  4.,  4.,  0.,  1.],
       [ 0.,  0.,  4.,  0., -1.,  0.],
       [ 0.,  0.,  8.,  4.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  8.,  4.]]), array([[-8.],
       [-8.],
       [-8.],
       [-8.],
       [-8.],
       [-8.]]), 12)
